name: Auto approve Dependabot PRs
on: pull_request

jobs:
  approve:
    name: Auto-approve dependabot PRs
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
