name: Push Heimdall-Lite to NPM and GitHub Packages and Push InspecJs to NPM
on:
  release:
    types: [published]
env:
  NODE_ENV: production
jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --production

      - name: Pack all items that are published as packages
        run: yarn pack:all

      - name: Publish Heimdall Lite to NPM
        if: always()
        run: npm publish --access public apps/frontend/mitre-heimdall-lite*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish InSpecJS to NPM
        if: always()
        run: npm publish --access public libs/inspecjs/inspecjs*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish HDF Converters to NPM
        if: always()
        run: npm publish --access public libs/hdf-converters/mitre-hdf-converters*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        if: always()
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'

      - name: Publish Heimdall Lite to GitHub Packages
        if: always()
        run: npm publish --access public apps/frontend/mitre-heimdall-lite*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
