name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
     - uses: actions/checkout@v2
     - name: Setup Node.js
       uses: actions/setup-node@v1
       with:
        node-version: '12.x'

     - name: Install dependencies
       run: npm ci

     - name: Run lint
       run: npm run lint:ci

     - name: Copy .env-ci to .env
       run: cp test/.env-ci .env

     - name: Create/migrate db
       run: |
         npx sequelize-cli db:create
         npx sequelize-cli db:migrate
         
     - name: Checkout frontend
       uses: actions/checkout@v2
       with:
         ref: heimdall2
         repository: mitre/heimdall-lite
         path: client

     - name: Build frontend
       run: |
         npm install
         npm run build 
       working-directory: client
       
     - name: Run test coverage
       run: npm run test:ci-cov

     - name: Run e2e tests
       run: npm run test:e2e
       
     - name: Run application
       run: npm run start &
       
     - name: sleep 30
       run: sleep 30
       
     - name: run curl
       run: curl localhost:3000
       
     - name: Run e2e UI tests
       run: npm run test:ui
